#! /usr/bin/env bash
# vim: filetype=sh

display_help() {
    echo "Usage: $0 [option...] < [content_file]" >&2
    echo
    echo "   -k, --project-key          The key of the confluence project"
    echo "   -t, --title                The title of the page"
    echo "   -a, --ancestor             The parent page id to create the new page under"
    echo "   -i, --id                   The id of page to update"
    echo "   -c, --creds-file           The credentials file in basic auth format.  default: ~/.ssh/jira_creds"
    echo
    # echo some stuff here for the -a or --add-options
    exit 1
}

METHOD=POST
CREDS_FILE=~/.ssh/jira_creds

while [ -n "$1" ]; do
    case "$1" in
      --project-key|-k)
       PROJECT_KEY="$2" ;;
      --title|-t)
       PAGE_TITLE="$2" ;;
      --ancestor|-a)
       ANCESTOR_ID="{'id':'$2'}" ;;
      --id|-i)
       ID="'id':'$2',"
       METHOD=PUT ;;
      --creds-file|-c)
       CREDS_FILE="$2" ;;
      --help|-h)
       display_help ;;
    * )
        ;;
    esac
    shift
done

if [[ -z "$PROJECT_KEY" ]]; then
  echo "Must supply project key"
  exit 1
fi

if [[ -z "$PAGE_TITLE" ]]; then
  echo "Must supply page title"
  exit 1
fi

CONTENT=$(cat <&0)
DATA="{$ID'type':'page','title':'$PAGE_TITLE','space':{'key':'$PROJECT_KEY'},'ancestors':[$ANCESTOR_ID],'body':{'storage':{'value':'$CONTENT','representation':'storage'}}}"

echo -n "${DATA//\'/\"}" > ./jira_upload

echo "JIRA UPLOAD CONTENT"

cat ./jira_upload

#curl -L -v -u $(cat "$CREDS_FILE") -X "$METHOD" -H 'Content-Type: application/json' -d @./jira_upload \
 #https://uk-gov-dft.atlassian.net/wiki/rest/api/content
